name: ${pluginName}
#description: Plugin description for ${pluginName}
version: ${project.parent.version}
api-version: '1.15'

# TODO: Use maven variables again
main: de.sprax2013.betterchairs.BetterChairsPlugin

author: BlackScarx
authors: [BlackScarx, Sprax2013]
website: https://github.com/Sprax2013/BetterChairs

commands:
  betterchairsreload:
    description: Reload the config
    aliases:
      - bcreload
      - bcr
    permission: ${pluginName}.reload
  betterchairstoggle:
    description: Command betterchairstoggle
    aliases:
      - bctoggle
      - bct
    permission: ${pluginName}.toggle
  betterchairsreset:
    description: Command betterchairsreset
    aliases:
      - bcreset
    permission: ${pluginName}.reset

permissions:
  ${pluginName}.use:
    description: Use the stairs
    default: true
  ${pluginName}.regeneration:
    description: Grants regeneration to a player when sitting
  ${pluginName}.updater:
    descritpion: Permission for betterchairs update